### ISSUE TITLE
[Question] How to divide docs now that we have an organization

### ISSUE THREAD

**Issue by maxcao13** [rhat-openjdk-interns/cryostat-knowledge-hub#2]
Should this repo be a big repo containing all the useful things for every part of cryostat? For example, we would have subdirectories of `-web` `-core` `-reports` etc. Then this way if future openjdk interns at Red Hat happen to not work on `cryostat` anymore, then additionally, a new repo for whatever project can be opened and the `operator-knowledge-hub` can stay _somewhat_ more general.

**Comment by maxcao13** [comment]
@tthvo wanted to get your thoughts.

**Comment by tthvo** [comment]
Yeh I think you r right :D Originally, I thought of resembling the structure of cryostatio but now that you mention new interns might be working on something else. 

We can go this way :D I guess the operator-knowledge-hub can stay general and add a sub-dir for `cryostat-operator`.

**Comment by tthvo** [comment]
For scripts, I guess they should stay as top-level directory `/scripts` and maybe categorized within that. Just thinking of a tiring looking into each project sub-dir for scripts haha

**Comment by maxcao13** [comment]
That's true, I think it would be nice to have quick links to all the docs probably in the README to the repos so its not as annoying to actively search as well :-)
